name: Publish Node package
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: actions/checkout
        uses: actions/checkout@v1.2.0
      - name: actions/setup-node
        uses: actions/setup-node@v1.3.0
        with:
          node-version: "12.13.1"
      - name: npm install
        uses: jaid/action-npm-install@master
      - name: Jest
        uses: jaid/action-jest@master
      - name: Publish
        uses: jaid/action-publish@master
        with:
          npmPrepareScript: build:prod
          publishDirectory: dist/package/production
          githubToken: ${{ secrets.packagesToken }}
          npmToken: ${{ secrets.npmToken }}